on:
  issues:
    types: [opened]
  workflow_dispatch:  
    
jobs:
  auto-gen-pr:
    name: Open PR to Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.event.issue.title }}
    - uses: peter-evans/create-pull-request@v3
      name: pull-request
      with:
        commit-message: ${{ github.event.issue.title }}
        title: Pulling Issue \#${{ github.event.issue.number }} into development
        body: Fix issue
        branch: ${{ github.event.issue.title }}
        base: master
  
