on:
  issues:
    types: [opened]
  workflow_dispatch:  
    
jobs:
  auto-gen-pr:
    name: Open PR to Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: actions/github-script@v4
      name: Generate valid name from issue title
      env:
        title: ${{ github.event.issue.title }}
      id: set-name
      with:
        result-encoding: string
        script: |
         // Get the isue name
         var {title} = process.env;
         console.log(title);
         console.log( title.replace(/\s+/g, '-').toLowerCase());
         return title = title.replace(/\s+/g, '-').toLowerCase();
    - name: Create report file
      run: echo ${{ github.event.issue.number }}, ${{ github.event.issue.body }} > .issue
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: New issue generated #${{ github.event.issue.number }}
        title: '[ISSUE] ${{ github.event.issue.title }} '
        body: >
          This PR is auto-generated with regard to issue #${{ github.event.issue.number }}
        labels: issue, automated pr
        branch: ${{steps.set-name.outputs.result}}
        delete-branch: false

