on:
  issues:
    types: [opened]
  workflow_dispatch:  
    
jobs:
  auto-gen-pr:
    name: Open PR to Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: actions/github-script@v4
      name: Generate valid name from issue title
      env:
        title: ${{ github.event.issue.title }}
      id: set-name
      with:
        result-encoding: string
        script: |
         // Get the isue name
         var {title} = process.env;
         console.log(title);
         console.log( title.replace(/\s+/g, '-').toLowerCase());
         return title = title.replace(/\s+/g, '-').toLowerCase();
    - uses: peterjgrainger/action-create-branch@v2.0.1
      name: Create branch with name provided
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{steps.set-name.outputs.result}}
    - uses: actions/checkout@v2
      name: Checkout to new branch
      with:
        ref: ${{steps.set-name.outputs.result}}
    - name: create init file
      run: echo ${{ github.event.issue.title }} > .issue
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: default_author
        message: 'init'
        add: '.issue'
    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        source_branch: ${{steps.set-name.outputs.result}}
        destination_branch: "master"
        pr_title: "Pulling ${{steps.set-name.outputs.result}} into main"
        pr_body: "👑 *An automated PR*"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
 
