on:
  issues:
    types: [opened]
  workflow_dispatch:  
    
jobs:
  auto-gen-pr:
    name: Open PR to Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: actions/github-script@v4
      env:
        title: ${{ github.event.issue.title }}
      id: set-name
      with:
        result-encoding: string
        script: |
         // Get the isue name
         var {title} = process.env;
         console.log(title);
         console.log( title.replace(/\s+/g, '-').toLowerCase());
         return title = title.replace(/\s+/g, '-').toLowerCase();
    - uses: actions/checkout@v2
      with:
        ref: ${{steps.set-name.outputs.result}}
    - name: create init file
      run: echo ${{ github.event.issue.title }} > .issue
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: default_author
        message: 'init'
        add: '.issue'
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{steps.set-name.outputs.result}}
    - uses: peter-evans/create-pull-request@v3
      name: pull-request
      with:
        commit-message: ${{ github.event.issue.title }}
        title: Pulling Issue \#${{ github.event.issue.number }} into development
        body: Fix issue
        branch: ${{steps.set-name.outputs.result}}
        base: master
 
